"""Generation of a runnable Python script for the current dataset.

Lets a user take the analysis out of the app and into their own notebook. The
script is tailored to the dataset it was generated for — real filename, real
column names, real target.
"""

from __future__ import annotations

from app.services.profiling_service import BOOLEAN, CATEGORICAL, NUMERIC


def _column_list(names: list[str]) -> str:
    if not names:
        return "[]"
    body = ",\n    ".join(repr(name) for name in names)
    return f"[\n    {body},\n]"


def generate_analysis_script(metadata: dict, profile: dict, target: str | None) -> str:
    """A pandas profiling script, plus a scikit-learn pipeline if a target is given."""
    filename = metadata["filename"]
    groups = profile["column_groups"]
    numeric = groups[NUMERIC]
    categorical = groups[CATEGORICAL] + groups[BOOLEAN]

    lines = [
        '"""Generated by DataPilot AI.',
        "",
        f"Dataset: {filename} "
        f"({metadata['rows']:,} rows x {metadata['columns']} columns)",
        '"""',
        "",
        "import pandas as pd",
        "",
        f"df = pd.read_csv({filename!r})",
        "",
        "# --- Overview ----------------------------------------------------",
        'print(f"Rows: {len(df):,}  Columns: {df.shape[1]}")',
        'print(f"Duplicate rows: {df.duplicated().sum():,}")',
        "print(df.dtypes)",
        "",
        "# --- Missing values ----------------------------------------------",
        "missing = df.isna().sum()",
        "missing_pct = (missing / len(df) * 100).round(2)",
        'print(pd.DataFrame({"missing": missing, "percent": missing_pct}))',
        "",
        "# --- Column groups DataPilot detected ------------------------------",
        f"NUMERIC_COLUMNS = {_column_list(numeric)}",
        f"CATEGORICAL_COLUMNS = {_column_list(categorical)}",
        "",
    ]

    if numeric:
        lines += [
            "# --- Numeric summary ----------------------------------------------",
            "print(df[NUMERIC_COLUMNS].describe().T)",
            "",
            "# Outliers by the IQR rule, the same test DataPilot uses.",
            "for column in NUMERIC_COLUMNS:",
            "    values = pd.to_numeric(df[column], errors='coerce').dropna()",
            "    q1, q3 = values.quantile(0.25), values.quantile(0.75)",
            "    iqr = q3 - q1",
            "    outliers = ((values < q1 - 1.5 * iqr) | (values > q3 + 1.5 * iqr)).sum()",
            '    print(f"{column}: {outliers} outliers")',
            "",
        ]

    if categorical:
        lines += [
            "# --- Categorical frequencies ----------------------------------------",
            "for column in CATEGORICAL_COLUMNS:",
            '    print(f"\\n{column} ({df[column].nunique()} unique)")',
            "    print(df[column].value_counts().head(10))",
            "",
        ]

    if target:
        model_numeric = [name for name in numeric if name != target]
        model_categorical = [name for name in categorical if name != target]

        lines += [
            "# --- Model pipeline -------------------------------------------------",
            "from sklearn.compose import ColumnTransformer",
            "from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor",
            "from sklearn.impute import SimpleImputer",
            "from sklearn.model_selection import train_test_split",
            "from sklearn.pipeline import Pipeline",
            "from sklearn.preprocessing import OneHotEncoder, StandardScaler",
            "",
            f"TARGET = {target!r}",
            f"FEATURE_NUMERIC = {_column_list(model_numeric)}",
            f"FEATURE_CATEGORICAL = {_column_list(model_categorical)}",
            "",
            "data = df.dropna(subset=[TARGET])",
            "X = data[FEATURE_NUMERIC + FEATURE_CATEGORICAL]",
            "y = data[TARGET]",
            "",
            "preprocessor = ColumnTransformer([",
            '    ("numeric", Pipeline([',
            '        ("impute", SimpleImputer(strategy="median")),',
            '        ("scale", StandardScaler()),',
            "    ]), FEATURE_NUMERIC),",
            '    ("categorical", Pipeline([',
            '        ("impute", SimpleImputer(strategy="most_frequent")),',
            '        ("encode", OneHotEncoder(handle_unknown="ignore")),',
            "    ]), FEATURE_CATEGORICAL),",
            "])",
            "",
            "# Few distinct values means classification; otherwise predict the number.",
            "is_classification = y.nunique() <= 10 or not pd.api.types.is_numeric_dtype(y)",
            "estimator = (",
            "    RandomForestClassifier(n_estimators=150, random_state=42)",
            "    if is_classification",
            "    else RandomForestRegressor(n_estimators=150, random_state=42)",
            ")",
            "",
            'model = Pipeline([("preprocess", preprocessor), ("model", estimator)])',
            "",
            "X_train, X_test, y_train, y_test = train_test_split(",
            "    X, y, test_size=0.2, random_state=42",
            ")",
            "model.fit(X_train, y_train)",
            'print(f"Test score: {model.score(X_test, y_test):.4f}")',
            "",
        ]

    return "\n".join(lines)
